apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: create-iam
spec:
  compositeTypeRef:
    apiVersion: iam.crossplane.io/v1
    kind: Xiam
  mode: Pipeline
  pipeline:
  - step: create-iam-roles
    functionRef:
      name: function-iam
