apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xiams.iam.crossplane.io
spec:
  group: iam.crossplane.io
  names:
    kind: Xiam
    plural: xiams
  claimNames:
    kind: XiamClaim
    plural: xiamclaims
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                permissions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      policyDocument:
                        type: string
              required:
                - permissions