apiVersion: iam.crossplane.io/v1
kind: Xiam
metadata:
  name: {{ .Values.serviceName | lower }}
spec:
  permissions:
{{- range $path, $_ := .Files.Glob (printf "%s/*.json" .Values.policiesFolder) }}
{{- $filename := base $path }}
{{- $policyName := trimSuffix ".json" $filename }}
    - type: {{ $policyName | lower }}
      policyDocument: |
{{ $.Files.Get $path | nindent 8 }}
{{- end }}
